name: "Omega Zirkel Global Intercom Plugin"
main: de.omegazirkel.risingworld.GlobalIntercom
version: 0.9.0-SNAPSHOT
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "This Plugin enables chat between servers (Singleplayer too)"
license: EMS
website: coming soon